sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  api_key:
    secure: u/zC51yT5kRp0qq4HcXTjgIiervojMr9tPnY1z3ZPv/mlybQpx8nX5fbNQSAd0QseavMbyt9jdqEUaTO4OKG3LjF8m4XcsUF+9W9+SUIK+pDCHW7doW4+xKIDr3ZAu1MD88KnbZSjsAtfMZ/xfB2TLDID0T5mxHlvkPsFxupAPpBL8Qx79YvIfuaia+RzoR+fE4z53UH/usEBjPB1PI1zXviCH0u8BdOheWXqngG0qTF7z8OzInb/0GUuUMEnd58/hm34xuSv71TCJdDbmubE6VQ3R8VhR9EnhotA8OavGToht/7G/SxbWAY4BIj7SQYkW2CkgYXywUXdZ/16/keV1zreHfQnnkScc4O037nlKXQZY1APEQ0zpANyepJXl1DSO+1XkhdB92+Rp6bQWr8+P4AqOJo1sus0vQ1/mUjPSRwX0WwnqyVImvHUahQdxpog8Fp6Vu6ZkVsVWGyMLxRF3gWTGvWNFqESjZ/2P5SgiwydGyBFPbL04k/uXMKMAf7c0XYx2U/wPDAjXyiEDmgpIbIfgtmf8GSI06tLd42OwHKY9NxnX57tCc8UojPGwT0SACPZiGb7F/rMKUNyhpSkht6QiePjXN+z8+sgKdeNifthW5O2hbtR7H7+RFXPxxnxEnzZin0Vk+VX+4yeBX5ixCc/lli4hpeeYBDTjft2iM=
  on: heroku_production
  app: probot-bjl95

